### ISSUE TITLE
palmettopy.exceptions.EndpointDown

### ISSUE THREAD

**Issue by hhy150** [earthquakesan/palmetto-py#12]
When I was using the third party on python, there are some problems as follows:
palmettopy.exceptions.EndpointDown: http://palmetto.aksw.org/palmetto-webapp/service/cp?words=road%20vendor%20ford
What more, When I input the "http://palmetto.aksw.org/palmetto-webapp/service/cp?words=road%20vendor%20ford" to the address bar, it did not work yet. the error message as follows:
ERROR
The requested URL could not be retrieved
The following error was encountered while trying to retrieve the URL: http://palmetto.demos.dice-research.org/service/cp?

Connection to 131.234.28.86 failed.

The system returned: (111) Connection refused

The remote host or network may be down. Please try the request again.

**Comment by MichaelRoeder** [comment]
Thank you for using Palmetto. Unfortunately, the service is not available at the moment. The problem is related to the machines on which the service is deployed and, hence, not directly related to Palmetto itself. There is not much we as developers can do and we hope that the issues will be solved, soon.
I will update you as soon as I get news regarding this issue.

**Comment by hhy150** [comment]
ok, I get it. Thank you for your reply. And I am trying other way.

**Comment by MichaelRoeder** [comment]
Please use the endpoint at http://palmetto.cs.upb.de:8080/ for the time being.
