### ISSUE TITLE
Endpointdown

### ISSUE THREAD

**Issue by fkalb** [earthquakesan/palmetto-py#6]
Sorry to bother you with this problem again:

Apparently the Endpoint is not responding. I was following the last issue opened by liaoming999 and tried to run some requests today, but the endpoint seems to be down.  

Thanks in advance, great repository!

**Comment by MichaelRoeder** [comment]
Thanks for using Palmetto. However, this is the wrong repository for this type of issue since the palmetto-py project is a client library while the endpoint is in the [palmetto project](https://github.com/dice-group/palmetto).
If you encounter an issue regarding the endpoint, please report it there.

I restarted the endpoint. It should work now. Please note that if you want to process large volumes of data, you may want to download Palmetto and execute it locally.
